const reactEnv = import.meta.env;

export const {
  VITE_ENV: ENV,
  VITE_SENTRY_DSN: SENTRY_DSN,
  VITE_BASE_PATH: BASE_PATH,
  VITE_FIREBASE_API_KEY: FIREBASE_API_KEY,
  VITE_FIREBASE_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
  VITE_FIREBASE_DB_URL: FIREBASE_DB_URL,
  VITE_FIREBASE_PROJECT_ID: FIREBASE_PROJECT_ID,
  VITE_FIREBASE_STORAGE_BUCKET: FIREBASE_STORAGE_BUCKET,
  VITE_FIREBASE_MESSAGING_SENDER_ID: FIREBASE_MESSAGING_SENDER_ID,
  VITE_FIREBASE_APP_ID: FIREBASE_APP_ID,
  VITE_FIREBASE_MEASUREMENT_ID: FIREBASE_MEASUREMENT_ID,
  VITE_FIREBASE_VAPID_KEY: FIREBASE_VAPID_KEY,
  VITE_BUILDERS_ID_ANDROID: BUILDERS_ID_ANDROID,
  VITE_BUILDERS_ID_IOS: BUILDERS_ID_IOS,
  VITE_GMT_ID: GMT_ID,
  VITE_CLIENT_ID: CLIENT_ID,
} = reactEnv;
